[global]
ioengine=libaio
direct=1
iodepth=128
rw=write
bs=128k
numjobs=1
group_reporting=1
time_based=1
ramp_time=120s
runtime=180s

[job1]
name=job1
filename=/dev/vdb

[job2]
name=job2
filename=/dev/vdc

[job3]
name=job3
filename=/dev/vdd

[job4]
name=job4
filename=/dev/vde

[job5]
name=job5
filename=/dev/vdf

[job6]
name=job6
filename=/dev/vdg

[job7]
name=job7
filename=/dev/vdh

[job8]
name=job8
filename=/dev/vdi